### ISSUE TITLE
Missing /lib/adapter.js ?

### ISSUE THREAD

**Issue by eisbaw** [t4qjXH8N/ioBroker.google-sharedlocations#1]
Hey, I would love to test this but I have zero experience with Node and this ioBroker project.
If I just run under node, I get 'Cannot find js-controller' error message.

regards
Mark

**Comment by t4qjXH8N** [comment]
Hey Mark,

this is an Adapter for ioBroker ([Link](http://iobroker.net/)). It is not supposed to run alone, it should be be installed by the ioBroker admin. Then it runs in the ioBroker context, where js-controller can be found by this adapter.

Check out the ioBroker project, it is a really interesting piece of software. I hope I could help you.

**Comment by eisbaw** [comment]
Hi Christian,
Thank you very much. ioBroker looks very interesting to control my BLE thermostats.

In the meantime, I took the liberty to refactor the code into a standalone version:
https://github.com/eisbaw/google_shared_locations

regards
Mark
