### ISSUE TITLE
[Request] State of battery and last timestamp

### ISSUE THREAD

**Issue by obodeldog** [t4qjXH8N/ioBroker.google-sharedlocations#11]
Great adapter! Can you also include an object for "battery of smartphone" and an object for "last seen" (timestamp)?

**Comment by t4qjXH8N** [comment]
Done.

**Comment by obodeldog** [comment]
Wow, thanks. Are there informations about accuracy of the GPS?

**Comment by obodeldog** [comment]
One more question: Can the accuracy of the location also be called up? This is possible at Owntrack.

**Comment by t4qjXH8N** [comment]
I think I found it. It should be present in v1.5.0
