### ISSUE TITLE
Goefencing does not work

### ISSUE THREAD

**Issue by obodeldog** [t4qjXH8N/ioBroker.google-sharedlocations#16]
Maybe I'm too stupid to set it correctly. But I can't get the geofencing to work. But this feature was tested by you, right?

**Comment by pmaster555** [comment]
Made a new account, does not connect, works with the old one, what can it be? two-factor authentication is disabled

**Comment by t4qjXH8N** [comment]
Does your comment refer to the issue? I guess you are experiencing a connection problem. If you want help, set the adapter log level to debug and publish the logs here.

**Comment by slimline33** [comment]
do you allowed unsafe apps in google? https://support.google.com/accounts/answer/6010255?hl=de
