### ISSUE TITLE
Constant "security notifications" from Google 

### ISSUE THREAD

**Issue by Xyolyp** [t4qjXH8N/ioBroker.google-sharedlocations#17]
I'm constantly getting security notifications from Google because the instance performs a login every time the polling interval has passed. I would like to see an enhancement like keeping the logged in session active as long as the instance is running. That way I would only get a notification when the instance is started and not every ten minutes.

**Comment by t4qjXH8N** [comment]
If it turns to red you are right, the adapter tries to do a new login. Maybe ten minutes is too long? Maybe Google terminates the session due to inactivity.

**Comment by Xyolyp** [comment]
Google seems to have gotten it by now. I had to confirm it like a million times and now it doesn't ask anymore exept when I manually click the "get data now" button.
