### ISSUE TITLE
Proxy Website

### ISSUE THREAD

**Issue by Schweizer75** [t4qjXH8N/ioBroker.google-sharedlocations#25]
Konto eingeben, auf Speichern
One description is empty!

Also bei Geofence Name - Längen - Breitengrad - Radius - Benutzer (Keine auswahl möglich) ZaunID
Userid of Schweiz must not be empty

Also auf Geofences den User komplett löschen und Speichern ist möglich, der Adapter ist diesesmal vorher bereits Gelb

Daten gespeichert und auf Verbindung Testen kommt
Connection failed. Use the proxy method to retrieve the cookie.

Dann klicken wir mal den (Experimental Button) Proxy-Website
Es passiert wie erwartet... NIX keine Webseite, kein Cookie nix was ich eingeben kann

Der Adapter ist gelb und es gibt kein "please login manually" im log... 

> 
> google-sharedlocations.0 | 2019-04-15 18:51:49.621 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
> -- | -- | -- | --
> google-sharedlocations.0 | 2019-04-15 18:51:49.614 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
> google-sharedlocations.0 | 2019-04-15 18:51:49.610 | debug | [google auth] connectEnterVerificationEmail
> google-sharedlocations.0 | 2019-04-15 18:51:49.344 | debug | [google auth] Connection third stage additional verification needed.
> google-sharedlocations.0 | 2019-04-15 18:51:49.155 | debug | [google auth] Connection third stage
> google-sharedlocations.0 | 2019-04-15 18:51:49.152 | debug | [google auth] Connection second stage successful
> google-sharedlocations.0 | 2019-04-15 18:51:48.351 | debug | [google auth] Connection second State
> google-sharedlocations.0 | 2019-04-15 18:51:48.349 | debug | [google auth] Connection first stage successfull
> google-sharedlocations.0 | 2019-04-15 18:51:46.817 | debug | [google auth] Connection First State
> google-sharedlocations.0 | 2019-04-15 18:51:46.810 | info | Starting google shared locations adapter
> google-sharedlocations.0 | 2019-04-15 18:51:46.800 | info | starting. Version 1.5.4 in /opt/iobroker/node_modules/iobroker.google-sharedlocations, node: v8.15.0
> google-sharedlocations.0 | 2019-04-15 18:51:46.623 | debug | statesDB connected
> google-sharedlocations.0 | 2019-04-15 18:51:46.497 | debug | objectDB connected
> host.raspberrypi | 2019-04-15 18:51:38.137 | info | instance system.adapter.google-sharedlocations.0 started with pid 1097
> host.raspberrypi | 2019-04-15 18:51:36.190 | info | instance system.adapter.google-sharedlocations.0 terminated with code 0 (OK)
> google-sharedlocations.0 | 2019-04-15 18:51:36.111 | debug | [google auth] Connection logout.
> google-sharedlocations.0 | 2019-04-15 18:51:35.602 | info | cleaned everything up...
> google-sharedlocations.0 | 2019-04-15 18:51:35.601 | debug | [google auth] Connection logout.
> host.raspberrypi | 2019-04-15 18:51:35.596 | info | stopInstance system.adapter.google-sharedlocations.0 killing pid 32100
> host.raspberrypi | 2019-04-15 18:51:35.595 | info | stopInstance system.adapter.google-sharedlocations.0
> host.raspberrypi | 2019-04-15 18:51:35.594 | info | object change system.adapter.google-sharedlocations.0
> google-sharedlocations.0 | 2019-04-15 18:51:31.392 | debug | sendTo "checkConnection" to system.adapter.admin.0 from system.adapter.google-sharedlocations.0: false
> google-sharedlocations.0 | 2019-04-15 18:51:31.391 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
> google-sharedlocations.0 | 2019-04-15 18:51:31.390 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
> google-sharedlocations.0 | 2019-04-15 18:51:31.388 | debug | [google auth] connectEnterVerificationEmail
> google-sharedlocations.0 | 2019-04-15 18:51:31.101 | debug | [google auth] Connection third stage additional verification needed.
> google-sharedlocations.0 | 2019-04-15 18:51:30.920 | debug | [google auth] Connection third stage
> google-sharedlocations.0 | 2019-04-15 18:51:30.919 | debug | [google auth] Connection second stage successful
> google-sharedlocations.0 | 2019-04-15 18:51:30.308 | debug | [google auth] Connection second State
> google-sharedlocations.0 | 2019-04-15 18:51:30.307 | debug | [google auth] Connection first stage successfull
> google-sharedlocations.0 | 2019-04-15 18:51:29.743 | debug | [google auth] Connection First State
> google-sharedlocations.0 | 2019-04-15 18:51:23.938 | debug | system.adapter.admin.0: logging false
> google-sharedlocations.0 | 2019-04-15 18:51:17.396 | debug | sendTo "getUsersFromDB" to system.adapter.admin.0 from system.adapter.google-sharedlocations.0
> google-sharedlocations.0 | 2019-04-15 18:50:39.237 | debug | system.adapter.admin.0: logging true
> google-sharedlocations.0 | 2019-04-15 18:49:34.739 | debug | sendTo "checkConnection" to system.adapter.admin.0 from system.adapter.google-sharedlocations.0: false
> google-sharedlocations.0 | 2019-04-15 18:49:34.738 | debug | [google auth] Connection third stage failed due to an additional verification that could not be identified!
> google-sharedlocations.0 | 2019-04-15 18:49:34.737 | debug | [google auth] connectEnterVerificationEmail failed, error:Error: options.uri is a required argument
> google-sharedlocations.0 | 2019-04-15 18:49:34.732 | debug | [google auth] connectEnterVerificationEmail
> google-sharedlocations.0 | 2019-04-15 18:49:34.400 | debug | [google auth] Connection third stage additional verification needed.
> google-sharedlocations.0 | 2019-04-15 18:49:34.199 | debug | [google auth] Connection third stage
> google-sharedlocations.0 | 2019-04-15 18:49:34.197 | debug | [google auth] Connection second stage successful
> google-sharedlocations.0 | 2019-04-15 18:49:33.213 | debug | [google auth] Connection second State
> google-sharedlocations.0 | 2019-04-15 18:49:33.210 | debug | [google auth] Connection first stage successfull
> google-sharedlocations.0 | 2019-04-15 18:49:31.489 | debug | [google auth] Connection First State
> google-sharedlocations.0 | 2019-04-15 18:48:46.243 | debug | sendTo "getUsersFromDB" to system.adapter.admin.0 from system.adapter.google-sharedlocations.0
> google-sharedlocations.0 | 2019-04-15 18:48:02.116 | debug | system.adapter.admin.0: logging false

sobald ich die emial zur wiederherstellung eingebe kommt noch

> google-sharedlocations.0 | 2019-04-15 18:51:49.690 | debug | stateChange google-sharedlocations.0.info.connection  {"val":false,"ack":false,"ts":1555354309676,"q":0,"from":"system.adapter.google-sharedlocations.0","lc":1555267717263}
> -- | -- | -- | --
> google-sharedlocations.0 | 2019-04-15 18:51:49.623 | error | First connection failed.
> 

hinzu... grüsse Schweiz

**Comment by t4qjXH8N** [comment]
Ja, der den Master-Branch habe ich gestern zerschossen ... ich setze den mal zurück oder fixe das gleich

**Comment by t4qjXH8N** [comment]
Google erlaub keine Logins mehr ohne Javascript. Daher muss erst die Proxy-Lösung fertig werden.
