### ISSUE TITLE
Error and Authentification

### ISSUE THREAD

**Issue by vr6syncro** [t4qjXH8N/ioBroker.google-sharedlocations#4]
Moin,

2 Probleme habe ich aktuell.

Zum einen bekommt ich bei jeder Abfrage auf dem Handy die Meldung ich soll den Zugriff vom ioBroker freigeben. ( Das ist ja soweit richtig denn ich habe bei Google die 2 Faktoren Authentifizierung aktiviert.) Aber nach einmaliger Aktivierung sollte er das ja speichern tut es aber nicht.

Zum anderen bekomme folgende Fehler:

`

google-sharedlocations.0 | 2018-04-20 15:47:13.513 | info | terminating
-- | -- | -- | --
google-sharedlocations.0 | 2018-04-20 15:47:13.012 | info | cleaned everything up...
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at emitOne (events.js:96:13)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at Request. (/opt/iobroker/node_modules/iobroker.google-sharedlocations/node_modules/request/request.js:1163:10)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at Request.emit (events.js:191:7)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at emitTwo (events.js:106:13)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.google-sharedlocations/node_modules/request/request.js:186:22)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:537:9)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at parseLocationData (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:633:18)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at /opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:541:26
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at /opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:176:7
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | at checkFences (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:444:29)
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | TypeError: Cannot read property 'length' of undefined
google-sharedlocations.0 | 2018-04-20 15:47:13.011 | error | uncaught exception: Cannot read property 'length' of undefined
google-sharedlocations.0 | 2018-04-20 15:47:13.007 | info | Checking fences.
google-sharedlocations.0 | 2018-04-20 15:47:12.326 | info | Third stage, password challenge ...
google-sharedlocations.0 | 2018-04-20 15:47:12.099 | info | Second stage, sending username ...
google-sharedlocations.0 | 2018-04-20 15:47:11.885 | info | Send username, connecting to Google ...
google-sharedlocations.0 | 2018-04-20 15:47:11.884 | info | Starting google shared locations adapter
google-sharedlocations.0 | 2018-04-20 15:47:11.876 | info | starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.google-sharedlocations, node: v6.14.1
google-sharedlocations.0 | 2018-04-20 15:46:41.253 | info | terminating
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | info | cleaned everything up...
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at emitOne (events.js:96:13)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at Request. (/opt/iobroker/node_modules/iobroker.google-sharedlocations/node_modules/request/request.js:1163:10)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at Request.emit (events.js:191:7)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at emitTwo (events.js:106:13)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at Request.self.callback (/opt/iobroker/node_modules/iobroker.google-sharedlocations/node_modules/request/request.js:186:22)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:537:9)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at parseLocationData (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:633:18)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at /opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:541:26
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at /opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:176:7
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | at checkFences (/opt/iobroker/node_modules/iobroker.google-sharedlocations/main.js:444:29)
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | TypeError: Cannot read property 'length' of undefined
google-sharedlocations.0 | 2018-04-20 15:46:40.751 | error | uncaught exception: Cannot read property 'length' of undefined
google-sharedlocations.0 | 2018-04-20 15:46:40.746 | info | Checking fences.
google-sharedlocations.0 | 2018-04-20 15:46:40.126 | info | Third stage, password challenge ...
google-sharedlocations.0 | 2018-04-20 15:46:39.914 | info | Second stage, sending username ...
google-sharedlocations.0 | 2018-04-20 15:46:39.710 | info | Send username, connecting to Google ...
google-sharedlocations.0 | 2018-04-20 15:46:39.710 | info | Starting google shared locations adapter
google-sharedlocations.0 | 2018-04-20 15:46:39.701 | info | starting. Version 0.0.4 in /opt/iobroker/node_modules/iobroker.google-sharedlocations, node: v6.14.1
google-sharedlocations.0 | 2018-04-20 15:46:09.093 | info | terminating

`

**Comment by t4qjXH8N** [comment]
Hey,

die zwei Faktor authorisierung muss ausgeschaltet sein für den Account den der ioBroker nutzt. Der zweiten Fehler habe ich behoben aber noch nicht commited, dieser tritt nur auf wenn kein Fence angelegt ist.
