### ISSUE TITLE
Adapter bleibt gelb

### ISSUE THREAD

**Issue by dslraser** [t4qjXH8N/ioBroker.google-sharedlocations#8]
Ich habe schon verschiedene Sachen ausprobiert, aber der Adapter verbindet sich nicht...? 
Was kommt bei Benutzername rein ? (habe meine E-Mail vom Google Account genommen, einen Benutzernamen habe/kenne ich nicht)
Was kommt bei Überprüfungs E-Mail rein ? (auch die Google E-Mail, oder die alternativen E-Mail Adressen zur Account Wiederherstellung ?)

**Comment by t4qjXH8N** [comment]
Als Benutzername die Gmail-Adresse des Accounts benutzen. Bei Überprüfungs E-Mail kommt die E-Mail Adresse zur Account Wiederherstellung rein. Zwei-Faktor Authentifizierung muss abgestellt sein. Wenn das nicht klappt, bitte die Log-Einträge posten.

**Comment by dslraser** [comment]
funktioniert jetzt. ich hatte ein Problem mit meinem Google Konto.
