### ISSUE TITLE
Benutzer ID und Objekte

### ISSUE THREAD

**Issue by dslraser** [t4qjXH8N/ioBroker.google-sharedlocations#9]
was muss bei GEOFENCES Benutzer ID eingetragen werden ?
welche Objekte sollten unter google-sharelocations.0 zu finden sein ? Ich bekomme nur info connection true/false. Sonst keine Daten...

**Comment by t4qjXH8N** [comment]
Wenn man keine Daten bekommt werden entweder keine Standorte mit dem angemelden Benutzer geteilt, oder es liegt ein Fehler vor. Die BentzerID unter geofences erhält man nach dem ersten Start des Adapters. Dazu Objekte aufrufen und unter "googleshared-locations.0.users" die ID auslesen. Das ist etwas umständlich, einen komfortableren Weg könnte ich irgendwann mal implementieren. Dieses Vorgehen ist auch unter "Usage" kurz beschrieben.

**Comment by dslraser** [comment]
okay danke, ich habe es hinbekommen. Wie stelle ich nun die Verbindung zum places Adapter her ? Ich habe places.0 eingetrage, ist das richtig ? (ich habe nur eine Instanz)

**Comment by t4qjXH8N** [comment]
Müsste klappen. Ich habe die Verbindung zum Places-Adapter vor einiger Zeit getestet, da ging es noch. Bitte um kurze Rückmeldung ob es funktioniert.

**Comment by dslraser** [comment]
bisher funktioniert es nicht, muss aber nicht an Deinem Adapter liegen. Ich bekomme auch über owntracks keine Auswertung im places Adapter. Ich habe dem Entwickler ein Log geschickt, mal sehen.

**Comment by dslraser** [comment]
Ich habe mir nun den Places Adapter 0.6.1 installiert (der Entwickler hat ein Update zur Verfügung gestellt) Nun funktioniert erstmal alles. Ich werde das jetzt mal etwas testen. Danke für die Hilfe und Deinen Adapter.
